# DigitalOcean App Platform spec
# Replace YOUR_GITHUB_USERNAME with your GitHub username and push this repo to GitHub.
# Then: doctl apps create --spec .do/app.yaml
# Or connect the repo at cloud.digitalocean.com/apps and use this spec.

name: world-health-portal
region: nyc1

# Backend API (Node.js)
services:
  - name: backend
    github:
      repo: shayer2009/healthcare-rn-platform
      branch: main
      deploy_on_push: true
    source_dir: backend
    run_command: node src/server.js
    environment_slug: node-js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8080"
        type: GENERAL
      - key: NODE_ENV
        value: production
        type: GENERAL
      # Add these in App Platform UI or via doctl (secrets):
      # DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME, JWT_SECRET
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

# Admin panel (optional static site - uncomment and set repo)
# static_sites:
#   - name: admin-panel
#     github:
#       repo: shayer2009/healthcare-rn-platform
#       branch: main
#     source_dir: admin-panel
#     build_command: npm ci && npm run build
#     output_dir: dist
#     environment_slug: node-js
#     routes:
#       - path: /
